### ISSUE TITLE
slack-chat:toggle does nothing

### ISSUE THREAD

**Issue by asarenski** [callahanrts/slack-chat#1]
Hi, so I was just taking a look at this. I installed it to atom and read the docs. After installation command+M does nothing. Is there something I'm missing?

**Comment by callahanrts** [comment]
Can you post what's displaying in `cmd + .` when you try command+M? Also, you can bind the slack-chat window toggle to any keybinding with something like this in your keymap: 

```
'.body':
    'cmd-m': "slack-chat:toggle"
```

**Comment by asarenski** [comment]
@callahanrts I tried looking into this a little bit, but I couldn't figure it out. Also I'm new to Atom.

**Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".**

**Comment by asarenski** [comment]
@callahanrts I've gotten to a solution but I'm having trouble implementing the solution.

```
npm install loophole
```

This installs a package called loophole, which allows you to use third-party packages in Atom.
https://github.com/atom/loophole

Some of the code then needs to be fixed by requiring loophole and using it.

**Comment by autoferrit** [comment]
I am having the same issue. when I try `cmd .` i get what is shown in the link below (bound to f10 so that i knew it didnt have a conflict)

http://screencast.com/t/Fc3hJQDRwc

the prompt at the bottom was all green. didnt seem like it had any issues. it just doesnt open.

I am running atom v0.150.0 . I have also noticed, that in the actual settings page, I don't have the option to put in my api key and related info.

**Comment by callahanrts** [comment]
Ok. I'm seeing the issue now too. I'll take a look at it in a couple of weeks when finals are over. Until then, feel free to submit a pull request if you discover the issue.

**Comment by ghost** [comment]
Did this ever get fixed? It doesn't work at all for me, same issues.

**Comment by deadbits** [comment]
Looks to be a keybinding conflict with cmd-m being 'minimize application' in Atom. Also, Atom is telling me to use the `atom-workspace` class instead of simply `.workspace`, though this doesn't appear to fix anything either

<pre>
    'atom-workspace':
        'cmd-m': 'slack-chat:toggle'
        'ctrl-o': 'slack-chat:open-conversation'
        'shift-enter': 'slack-chat:new-line'
</pre>

**Comment by callahanrts** [comment]
It looks like most of the issues are due to age. I've missed quite a few major updates with this. Unfortunately, I don't use Atom anymore so I haven't been very good at maintaining this project. If someone wants to go through the [upgrade guides](https://atom.io/docs/latest/upgrading/upgrading-your-package) and make a pull request, I'd gladly merge it. Likewise, if anyone is interesting in maintaining this project, I can give you the permissions needed. 
The latest workflow seems to be: 

```
apm develop slack-chat # clones the repo
cd ~/.atom/dev/packages/slack-chat

# Start atom in developer mode with the slack-chat package installed
atom -d 
```

**Comment by asarenski** [comment]
@callahanrts Cody, can you please give me permission? I know how to update the package so that it works.

**Comment by ghost** [comment]
@asarenski Yay! @callahanrts Stoked to see this working again!

**Comment by asarenski** [comment]
@callahanrts Merged my pull request. As stated, there is still more work to be done, but this problem has been solved.
